"""column name hide_link changed to photo_id

Revision ID: 079bf39c2d47
Revises: 8411c8f9a39e
Create Date: 2022-05-10 20:40:03.006957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079bf39c2d47'
down_revision = '8411c8f9a39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('photo_id', sa.String(), nullable=True))
    op.drop_column('holidays', 'hide_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('hide_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('holidays', 'photo_id')
    # ### end Alembic commands ###
