"""initial

Revision ID: 26fe84a025e6
Revises: 
Create Date: 2022-04-26 18:12:01.856157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fe84a025e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('uid', sa.String(length=10), nullable=False),
    sa.Column('holiday_name', sa.String(length=255), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('hide_link', sa.String(), nullable=True),
    sa.Column('hn_en', sa.String(), nullable=True),
    sa.Column('hn_uz', sa.String(), nullable=True),
    sa.Column('hn_ua', sa.String(), nullable=True),
    sa.Column('hn_es', sa.String(), nullable=True),
    sa.Column('hn_fr', sa.String(), nullable=True),
    sa.Column('where', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name='holidays_pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holidays')
    # ### end Alembic commands ###
