"""initial

Revision ID: 78b8f49ec3e3
Revises: 
Create Date: 2022-04-24 15:31:11.582633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b8f49ec3e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('hn_ru', sa.String(), nullable=True))
    op.add_column('holidays', sa.Column('uz_ru', sa.String(), nullable=True))
    op.add_column('holidays', sa.Column('ua_ru', sa.String(), nullable=True))
    op.add_column('holidays', sa.Column('es_ru', sa.String(), nullable=True))
    op.add_column('holidays', sa.Column('fr_ru', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holidays', 'fr_ru')
    op.drop_column('holidays', 'es_ru')
    op.drop_column('holidays', 'ua_ru')
    op.drop_column('holidays', 'uz_ru')
    op.drop_column('holidays', 'hn_ru')
    # ### end Alembic commands ###
