"""message_id column add

Revision ID: 8411c8f9a39e
Revises: 26fe84a025e6
Create Date: 2022-05-10 16:27:50.624472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8411c8f9a39e'
down_revision = '26fe84a025e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('message_id', sa.Integer(), nullable=True))
    op.drop_column('holidays', 'where')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('where', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('holidays', 'message_id')
    # ### end Alembic commands ###
